

element_names = [
    {'label': 'Hydrogen', 'value': 'Hydrogen'},
    {'label': 'Helium', 'value': 'Helium'},
    {'label': 'Lithium', 'value': 'Lithium'},
    {'label': 'Beryllium', 'value': 'Beryllium'},
    {'label': 'Boron', 'value': 'Boron'},
    {'label': 'Carbon', 'value': 'Carbon'},
    {'label': 'Nitrogen', 'value': 'Nitrogen'},
    {'label': 'Oxygen', 'value': 'Oxygen'},
    {'label': 'Fluorine', 'value': 'Fluorine'},
    {'label': 'Neon', 'value': 'Neon'},
    {'label': 'Sodium', 'value': 'Sodium'},
    {'label': 'Magnesium', 'value': 'Magnesium'},
    {'label': 'Aluminium', 'value': 'Aluminium'},
    {'label': 'Silicon', 'value': 'Silicon'},
    {'label': 'Phosphorus', 'value': 'Phosphorus'},
    {'label': 'Sulfur', 'value': 'Sulfur'},
    {'label': 'Chlorine', 'value': 'Chlorine'},
    {'label': 'Argon', 'value': 'Argon'},
    {'label': 'Potassium', 'value': 'Potassium'},
    {'label': 'Calcium', 'value': 'Calcium'},
    {'label': 'Scandium', 'value': 'Scandium'},
    {'label': 'Titanium', 'value': 'Titanium'},
    {'label': 'Vanadium', 'value': 'Vanadium'},
    {'label': 'Chromium', 'value': 'Chromium'},
    {'label': 'Manganese', 'value': 'Manganese'},
    {'label': 'Iron', 'value': 'Iron'},
    {'label': 'Cobalt', 'value': 'Cobalt'},
    {'label': 'Nickel', 'value': 'Nickel'},
    {'label': 'Copper', 'value': 'Copper'},
    {'label': 'Zinc', 'value': 'Zinc'},
    {'label': 'Gallium', 'value': 'Gallium'},
    {'label': 'Germanium', 'value': 'Germanium'},
    {'label': 'Arsenic', 'value': 'Arsenic'},
    {'label': 'Selenium', 'value': 'Selenium'},
    {'label': 'Bromine', 'value': 'Bromine'},
    {'label': 'Krypton', 'value': 'Krypton'},
    {'label': 'Rubidium', 'value': 'Rubidium'},
    {'label': 'Strontium', 'value': 'Strontium'},
    {'label': 'Yttrium', 'value': 'Yttrium'},
    {'label': 'Zirconium', 'value': 'Zirconium'},
    {'label': 'Niobium', 'value': 'Niobium'},
    {'label': 'Molybdenum', 'value': 'Molybdenum'},
    {'label': 'Technetium', 'value': 'Technetium'},
    {'label': 'Ruthenium', 'value': 'Ruthenium'},
    {'label': 'Rhodium', 'value': 'Rhodium'},
    {'label': 'Palladium', 'value': 'Palladium'},
    {'label': 'Silver', 'value': 'Silver'},
    {'label': 'Cadmium', 'value': 'Cadmium'},
    {'label': 'Indium', 'value': 'Indium'},
    {'label': 'Tin', 'value': 'Tin'},
    {'label': 'Antimony', 'value': 'Antimony'},
    {'label': 'Tellurium', 'value': 'Tellurium'},
    {'label': 'Iodine', 'value': 'Iodine'},
    {'label': 'Xenon', 'value': 'Xenon'},
    {'label': 'Caesium', 'value': 'Caesium'},
    {'label': 'Barium', 'value': 'Barium'},
    {'label': 'Lanthanum', 'value': 'Lanthanum'},
    {'label': 'Cerium', 'value': 'Cerium'},
    {'label': 'Praseodymium', 'value': 'Praseodymium'},
    {'label': 'Neodymium', 'value': 'Neodymium'},
    {'label': 'Promethium', 'value': 'Promethium'},
    {'label': 'Samarium', 'value': 'Samarium'},
    {'label': 'Europium', 'value': 'Europium'},
    {'label': 'Gadolinium', 'value': 'Gadolinium'},
    {'label': 'Terbium', 'value': 'Terbium'},
    {'label': 'Dysprosium', 'value': 'Dysprosium'},
    {'label': 'Holmium', 'value': 'Holmium'},
    {'label': 'Erbium', 'value': 'Erbium'},
    {'label': 'Thulium', 'value': 'Thulium'},
    {'label': 'Ytterbium', 'value': 'Ytterbium'},
    {'label': 'Lutetium', 'value': 'Lutetium'},
    {'label': 'Hafnium', 'value': 'Hafnium'},
    {'label': 'Tantalum', 'value': 'Tantalum'},
    {'label': 'Tungsten', 'value': 'Tungsten'},
    {'label': 'Rhenium', 'value': 'Rhenium'},
    {'label': 'Osmium', 'value': 'Osmium'},
    {'label': 'Iridium', 'value': 'Iridium'},
    {'label': 'Platinum', 'value': 'Platinum'},
    {'label': 'Gold', 'value': 'Gold'},
    {'label': 'Mercury', 'value': 'Mercury'},
    {'label': 'Thallium', 'value': 'Thallium'},
    {'label': 'Lead', 'value': 'Lead'},
    {'label': 'Bismuth', 'value': 'Bismuth'},
    {'label': 'Polonium', 'value': 'Polonium'},
    {'label': 'Astatine', 'value': 'Astatine'},
    {'label': 'Radon', 'value': 'Radon'},
    {'label': 'Francium', 'value': 'Francium'},
    {'label': 'Radium', 'value': 'Radium'},
    {'label': 'Actinium', 'value': 'Actinium'},
    {'label': 'Thorium', 'value': 'Thorium'},
    {'label': 'Protactinium', 'value': 'Protactinium'},
    {'label': 'Uranium', 'value': 'Uranium'},
    {'label': 'Neptunium', 'value': 'Neptunium'},
    {'label': 'Plutonium', 'value': 'Plutonium'},
    {'label': 'Americium', 'value': 'Americium'},
    {'label': 'Curium', 'value': 'Curium'},
    {'label': 'Berkelium', 'value': 'Berkelium'},
    {'label': 'Californium', 'value': 'Californium'},
    {'label': 'Einsteinium', 'value': 'Einsteinium'},
    {'label': 'Fermium', 'value': 'Fermium'},
    {'label': 'Mendelevium', 'value': 'Mendelevium'},
    {'label': 'Nobelium', 'value': 'Nobelium'},
    {'label': 'Lawrencium', 'value': 'Lawrencium'},
    {'label': 'Rutherfordium', 'value': 'Rutherfordium'},
    {'label': 'Dubnium', 'value': 'Dubnium'},
    {'label': 'Seaborgium', 'value': 'Seaborgium'},
    {'label': 'Bohrium', 'value': 'Bohrium'},
    {'label': 'Hassium', 'value': 'Hassium'},
    {'label': 'Meitnerium', 'value': 'Meitnerium'},
    {'label': 'Darmstadtium', 'value': 'Darmstadtium'},
    {'label': 'Roentgenium', 'value': 'Roentgenium'},
    {'label': 'Copernicium', 'value': 'Copernicium'},
    {'label': 'Nihonium', 'value': 'Nihonium'},
    {'label': 'Flerovium', 'value': 'Flerovium'},
    {'label': 'Moscovium', 'value': 'Moscovium'},
    {'label': 'Livermorium', 'value': 'Livermorium'},
    {'label': 'Tennessine', 'value': 'Tennessine'},
    {'label': 'Oganesson', 'value': 'Oganesson'},
]


reaction_names = [
    {'label': 'MT 1 (n,total)', 'value': 'total'},
    {'label': 'MT 2 (n,elastic)', 'value': 2},
    {'label': 'MT 3 (n,nonelastic)', 'value':  3},
    {'label': 'MT 4 (n,level)', 'value': 4},
    {'label': 'MT 5 (n,misc)', 'value':  5},
    {'label': 'MT 11 (n,2nd)', 'value':  11},
    {'label': 'MT 16 (n,2n)', 'value':  16},
    {'label': 'MT 17 (n,3n)', 'value': 17},
    {'label': 'MT 18 (n,fission)', 'value':  18},
    {'label': 'MT 19 (n,f)', 'value':  19},
    {'label': 'MT 20 (n,nf)', 'value':  20},
    {'label': 'MT 21 (n,2nf)', 'value': 21},
    {'label': 'MT 22 (n,na)', 'value':  22},
    {'label': 'MT 23 (n,n3a)', 'value':  23},
    {'label': 'MT 24 (n,2na)', 'value':  24},
    {'label': 'MT 25 (n,3na)', 'value': 25},
    {'label': 'MT 27 (n,absorption)', 'value':  27},
    {'label': 'MT 28 (n,np)', 'value':  28},
    {'label': 'MT 29 (n,n2a)', 'value': 29},
    {'label': 'MT 30 (n,2n2a)', 'value':  30},
    {'label': 'MT 32 (n,nd)', 'value':  32},
    {'label': 'MT 33 (n,nt)', 'value':  33},
    {'label': 'MT 34 (n,nHe-3)', 'value': 34},
    {'label': 'MT 35 (n,nd2a)', 'value':  35},
    {'label': 'MT 36 (n,nt2a)', 'value':  36},
    {'label': 'MT 37 (n,4n)', 'value':  37},
    {'label': 'MT 38 (n,3nf)', 'value': 38},
    {'label': 'MT 41 (n,2np)', 'value':  41},
    {'label': 'MT 42 (n,3np)', 'value':  42},
    {'label': 'MT 44 (n,n2p)', 'value':  44},
    {'label': 'MT 45 (n,npa)', 'value': 45},
    {'label': 'MT 91 (n,nc)', 'value':  91},
    {'label': 'MT 101 (n,disappear)', 'value':  101},
    {'label': 'MT 102 (n,gamma)', 'value': 102},
    {'label': 'MT 103 (n,p)', 'value':  103},
    {'label': 'MT 104 (n,d)', 'value':  104},
    {'label': 'MT 105 (n,t)', 'value':  105},
    {'label': 'MT 106 (n,3He)', 'value': 106},
    {'label': 'MT 107 (n,a)', 'value':  107},
    {'label': 'MT 108 (n,2a)', 'value':  108},
    {'label': 'MT 109 (n,3a)', 'value':  109},
    {'label': 'MT 111 (n,2p)', 'value': 111},
    {'label': 'MT 112 (n,pa)', 'value':  112},
    {'label': 'MT 113 (n,t2a)', 'value':  113},
    {'label': 'MT 114 (n,d2a)', 'value':  114},
    {'label': 'MT 115 (n,pd)', 'value': 115},
    {'label': 'MT 116 (n,pt)', 'value':  116},
    {'label': 'MT 117 (n,da)', 'value':  117},
    {'label': 'MT 152 (n,5n)', 'value':  152},
    {'label': 'MT 153 (n,6n)', 'value': 153},
    {'label': 'MT 154 (n,2nt)', 'value':  154},
    {'label': 'MT 155 (n,ta)', 'value':  155},
    {'label': 'MT 156 (n,4np)', 'value':  156},
    {'label': 'MT 157 (n,3nd)', 'value': 157},
    {'label': 'MT 158 (n,nda)', 'value':  158},
    {'label': 'MT 159 (n,2npa)', 'value':  159},
    {'label': 'MT 160 (n,7n)', 'value':  160},
    {'label': 'MT 161 (n,8n)', 'value': 161},
    {'label': 'MT 162 (n,5np)', 'value':  162},
    {'label': 'MT 163 (n,6np)', 'value':  163},
    {'label': 'MT 164 (n,7np)', 'value':  164},
    {'label': 'MT 165 (n,4na)', 'value': 165},
    {'label': 'MT 166 (n,5na)', 'value':  166},
    {'label': 'MT 167 (n,6na)', 'value':  167},
    {'label': 'MT 168 (n,7na)', 'value':  168},
    {'label': 'MT 169 (n,4nd)', 'value': 169},
    {'label': 'MT 170 (n,5nd)', 'value':  170},
    {'label': 'MT 171 (n,6nd)', 'value':  171},
    {'label': 'MT 172 (n,3nt)', 'value':  172},
    {'label': 'MT 173 (n,4nt)', 'value': 173},
    {'label': 'MT 174 (n,5nt)', 'value':  174},
    {'label': 'MT 175 (n,6nt)', 'value':  175},
    {'label': 'MT 176 (n,2n3He)', 'value': 176},
    {'label': 'MT 177 (n,3n3He)', 'value':  177},
    {'label': 'MT 178 (n,4n3He)', 'value':  178},
    {'label': 'MT 179 (n,3n2p)', 'value': 179},
    {'label': 'MT 180 (n,3n3a)', 'value':  180},
    {'label': 'MT 181 (n,3npa)', 'value':  181},
    {'label': 'MT 182 (n,dt)', 'value': 182},
    {'label': 'MT 183 (n,npd)', 'value':  183},
    {'label': 'MT 184 (n,npt)', 'value':  184},
    {'label': 'MT 185 (n,ndt)', 'value': 185},
    {'label': 'MT 186 (n,np3He)', 'value':  186},
    {'label': 'MT 187 (n,nd3He)', 'value':  187},
    {'label': 'MT 188 (n,nt3He)', 'value': 188},
    {'label': 'MT 189 (n,nta)', 'value':  189},
    {'label': 'MT 190 (n,2n2p)', 'value':  190},
    {'label': 'MT 191 (n,p3He)', 'value': 191},
    {'label': 'MT 192 (n,d3He)', 'value':  192},
    {'label': 'MT 193 (n,3Hea)', 'value':  193},
    {'label': 'MT 194 (n,4n2p)', 'value': 194},
    {'label': 'MT 195 (n,4n2a)', 'value':  195},
    {'label': 'MT 196 (n,4npa)', 'value':  196},
    {'label': 'MT 197 (n,3p)', 'value': 197},
    {'label': 'MT 198 (n,n3p)', 'value':  198},
    {'label': 'MT 199 (n,3n2pa)', 'value':  199},
    {'label': 'MT 200 (n,5n2p)', 'value':  200},
    {'label': 'MT 203 (n,Xp)', 'value': 203},
    {'label': 'MT 204 (n,Xd)', 'value': 204},
    {'label': 'MT 205 (n,Xt)', 'value': 205},
    {'label': 'MT 206 (n,3He)', 'value': 206},
    {'label': 'MT 207 (n,Xa)', 'value': 207},
    {'label': 'MT 301 (n,heat)', 'value': 301},
    {'label': 'MT 444 (n,damage)', 'value': 444},
    {'label': 'MT 649 (n,pc)', 'value':  649},
    {'label': 'MT 699 (n,dc)', 'value':  699},
    {'label': 'MT 749 (n,tc)', 'value':  749},
    {'label': 'MT 799 (n,3Hec)', 'value': 799},
    {'label': 'MT 849 (n,ac)', 'value':  849},
    {'label': 'MT 891 (n,2nc)', 'value': 891},
    {'label': 'MT 901 (n,displacement NRT)', 'value': 901},
]

for i in range(50, 91):
    reaction_names.append({'label': f'MT {i} (n,n{i-50})', 'value': i})

    # {'label[, ''MT '+str(i)+' (n,p{})'.format(i - 600) for i in range(600, 649)] +  'value':\  '+},
    # {'label[, ''MT '+str(i)+' (n,d{})'.format(i - 650) for i in range(650, 699)] +  'value':\  '+},
    # {'label[, ''MT '+str(i)+' (n,t{})'.format(i - 700) for i in range(700, 749)] +  'value':\  '+},
    # {'label[, ''MT '+str(i)+' (n,3He{})'.format(i - 750) for i in range(750, 799)] +  'value':\  '+},
    # {'label[, ''MT '+str(i)+' (n,a{})'.format(i - 800) for i in range(800, 849)] +  'value':\  '+},
    # {'label[, ''MT '+str(i)+' (n,2n{})'.format(i - 875) for i in range(875, 891) 'value':]  '+},
